[settings]
experimental = true

[tools]
# Environments
node = 'latest'
'github:nubjs/nub' = { version = 'latest', postinstall = 'nub pm pin' }
# Linters & Formatters
hk = 'latest'
stylua = 'latest'
pkl = 'latest'

[deps.nub]
description = 'Automatically install Node.js dependencies via nub.'
sources = ['package.json', 'nub.lock']
outputs = ['node_modules/']
run = 'nub install'
auto = true

[env]
_.path = ['{{config_root}}/node_modules/.bin']

# See https://github.com/webpro-nl/knip/issues/1813 & https://github.com/oxc-project/oxc/issues/11834
KNIP_DISABLE_RAW_TRANSFER = 1

[hooks]
# Only running self-update on Netlify,
# to update mise before installing tools,
# because Netlify's built-in mise is outdated.
preinstall = '''
test $NETLIFY && mise self-update
'''

[tasks.dev]
run = "vite --port 3333 --open"

[tasks.build]
env = { NODE_ENV = "production" }
run = [
  { task = "static" },
  "vite-ssg build",
  { tasks = [
    "copy-fonts",
    "rss",
  ] },
  { task = "redirects" },
]

[tasks.copy-fonts]
run = "nub ./scripts/copy-fonts.ts"

[tasks.rss]
run = "nub ./scripts/rss.ts"

[tasks.static]
run = [
  "premove temp",
  "git clone https://github.com/lumirelle/static temp",
  "premove temp/.git",
  "nub ./scripts/copy-sponsors.ts",
]

[tasks.redirects]
run = "nub ./scripts/redirects.ts"
depends_post = "copy-dist-redirects"

[tasks.copy-dist-redirects]
run = "nub ./scripts/copy-dist-redirects.ts"

[tasks.compress]
run = "nub ./scripts/img-compress-staged.ts"

[tasks.photos]
run = "nub ./scripts/photos-manage.ts"

[tasks.start]
run = "vite preview"

[tasks.check]
description = 'Run all checks.'
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk check {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''

[tasks.fix]
description = 'Fix all check issues.'
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk fix {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''
