[env]
_.path = [ "./node_modules/.bin" ]

[hooks]
# Only running self-update on Netlify,
# to update mise before installing tools,
# because Netlify's built-in mise is outdated.
preinstall = "bun run ./scripts/self-update-if-netlify.sh"

[tools]
# Environments
bun = "latest"
aube = "latest"
# Linters & Formatters
pkl = "latest"
hk = "latest"
# Build tools
"npm:premove" = "latest"

[deps.bun-aube]
sources = [
  "package.json",
  "bun.lock"
]
outputs = [ "node_modules/" ]
# Because aube's output lockfile has bugs,
# we use `bun install --lockfile-only` to generate a lockfile
run = "bun install --lockfile-only && aube install"
auto = true

[tasks.dev]
run = "vite --port 3333 --open"

[tasks.build]
env = { NODE_ENV = "production" }
run = [
  { task = "static" },
  "vite-ssg build",
  { tasks = [
    "copy-fonts",
    "rss"
  ] },
  { task = "redirects" },
]

[tasks.copy-fonts]
run = "bun run ./scripts/copy-fonts.ts"

[tasks.rss]
run = "bun run ./scripts/rss.ts"

[tasks.static]
run = [
  "premove temp",
  "git clone https://github.com/lumirelle/static temp",
  "premove temp/.git",
  "bun run ./scripts/copy-sponsors.ts"
]

[tasks.redirects]
run = "bun run ./scripts/redirects.ts"

[tasks.compress]
run = "bun run ./scripts/img-compress-staged.ts"

[tasks.photos]
run = "bun run ./scripts/photos-manage.ts"

[tasks.start]
run = "vite preview"

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"
