[env]
_.path = [ "./node_modules/.bin" ]

[tools]
bun = "latest"
aube = "latest"
pkl = "latest"
hk = "latest"

[hooks]
enter = [
  "hk install",
  { task = "prepare" },
  "if [[ $NETLIFY == true ]]; then mise self-update --yes; fi"
]

[deps.auto-aube]
sources = [
  "package.json",
  "bun.lock"
]
outputs = [ "node_modules/" ]
# Because aube's output lockfile has bugs,
# we use `bun install --lockfile-only` to generate a lockfile
run = "bun install --lockfile-only && aube install"
auto = true

[tasks.pre-commit]
run = "hk run pre-commit"

[tasks.prepare]
run = "bun run ./scripts/cert.ts"

[tasks.dev]
run = "vite --port 3333 --open"

[tasks.build]
env = { NODE_ENV = "production" }
run = [
  { task = "static" },
  "vite-ssg build",
  { tasks = [
    "copy-fonts",
    "rss"
  ] },
  { task = "redirects" },
]

[tasks.copy-fonts]
run = "bun run ./scripts/copy-fonts.ts"

[tasks.rss]
run = "bun run ./scripts/rss.ts"

[tasks.static]
run = [
  "aubx premove temp",
  "aubx degit lumirelle/static temp --force",
  "bun run ./scripts/copy-sponsors.ts"
]

[tasks.redirects]
run = "bun run ./scripts/redirects.ts"

[tasks.compress]
run = "bun run ./scripts/img-compress-staged.ts"

[tasks.photos]
run = "bun run ./scripts/photos-manage.ts"

[tasks.start]
depends = "vite preview"

[tasks.check]
run = "hk check --all"

[tasks.fix]
run = "hk fix --all"
