packages: []

catalogs:
  build:
    '@shikijs/markdown-it': ^3.15.0
    '@shikijs/transformers': ^3.15.0
    '@shikijs/twoslash': ^3.15.0
    '@unocss/preset-web-fonts': ^66.5.5
    '@vitejs/plugin-vue': ^6.0.1
    gray-matter: ^4.0.3
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-footnote: ^4.0.0
    markdown-it-github-alerts: ^1.0.0
    markdown-it-link-attributes: ^4.0.1
    markdown-it-magic-link: ^0.1.4
    markdown-it-table-of-contents: ^1.1.0
    unocss: ^66.5.5
    unplugin-auto-import: ^20.2.0
    unplugin-icons: ^22.5.0
    unplugin-vue-components: ^30.0.0
    unplugin-vue-markdown: ^29.2.0
    unplugin-vue-router: ^0.16.1
    vite: ^7.2.2
    vite-plugin-inspect: ^11.3.3
    vite-plugin-optimize-exclude: ^0.0.1
    vite-ssg: ^28.2.2
    vite-svg-loader: ^5.1.0
  dev:
    '@antfu/eslint-config': ^6.2.0
    '@clack/prompts': ^0.11.0
    '@iconify/json': ^2.2.405
    '@octokit/core': ^7.0.6
    '@octokit/rest': ^22.0.1
    '@prettier/plugin-xml': ^3.4.2
    ansis: ^4.2.0
    czg: ^1.12.0
    degit: ^2.8.4
    diacritics: ^1.3.0
    eslint: ^9.39.1
    eslint-plugin-format: ^1.0.2
    exifreader: ^4.32.0
    fast-glob: ^3.3.3
    feed: ^5.1.0
    fs-extra: ^11.3.2
    lint-staged: ^16.2.6
    pathe: ^2.0.3
    pnpm: ^10.21.0
    rimraf: ^6.1.0
    sharp: 0.32.6
    simple-git: ^3.30.0
    simple-git-hooks: ^2.13.1
    taze: ^19.9.0
    tsx: ^4.20.6
    typescript: ~5.9.3
  frontend:
    '@antfu/utils': ^9.3.0
    '@unhead/vue': ^2.0.19
    '@unocss/reset': ^66.5.5
    '@vueuse/core': ^14.0.0
    d3-hierarchy: ^3.1.2
    d3-shape: ^3.2.0
    dayjs: ^1.11.19
    floating-vue: ^5.2.2
    matter-attractors: ^0.1.6
    matter-js: ^0.20.0
    nprogress: ^0.2.0
    pinia: ^3.0.4
    pixi.js: ^8.14.1
    shiki: ^3.15.0
    shiki-magic-move: ^1.2.1
    simplex-noise: ^4.0.3
    vue: ^3.5.24
    vue-router: ^4.6.3
    vue-router-better-scroller: ^0.0.0
  types:
    '@types/d3-hierarchy': ^3.1.7
    '@types/d3-shape': ^3.1.7
    '@types/degit': ^2.8.6
    '@types/diacritics': ^1.3.3
    '@types/fs-extra': ^11.0.4
    '@types/markdown-it': ^14.1.2
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/node': ^24.10.0
    '@types/nprogress': ^0.2.3

onlyBuiltDependencies:
  - esbuild
  - exifreader
  - sharp
  - simple-git-hooks
  - unrs-resolver

shellEmulator: true
