/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/bookmarks': RouteRecordInfo<
      '/bookmarks',
      '/bookmarks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/demos': RouteRecordInfo<
      '/demos',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/media': RouteRecordInfo<
      '/media',
      '/media',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/notes': RouteRecordInfo<
      '/notes',
      '/notes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photos': RouteRecordInfo<
      '/photos',
      '/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/code-style-encapsulation-and-modularity': RouteRecordInfo<
      '/posts/code-style-encapsulation-and-modularity',
      '/posts/code-style-encapsulation-and-modularity',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/code-style-symbol-name-pattern': RouteRecordInfo<
      '/posts/code-style-symbol-name-pattern',
      '/posts/code-style-symbol-name-pattern',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-bash-script': RouteRecordInfo<
      '/posts/manual-bash-script',
      '/posts/manual-bash-script',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-computer-network': RouteRecordInfo<
      '/posts/manual-computer-network',
      '/posts/manual-computer-network',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-git': RouteRecordInfo<
      '/posts/manual-git',
      '/posts/manual-git',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-html-advanced-grammar': RouteRecordInfo<
      '/posts/manual-html-advanced-grammar',
      '/posts/manual-html-advanced-grammar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-js-advanced-grammar': RouteRecordInfo<
      '/posts/manual-js-advanced-grammar',
      '/posts/manual-js-advanced-grammar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-js-pm': RouteRecordInfo<
      '/posts/manual-js-pm',
      '/posts/manual-js-pm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-neovim-lazyvim': RouteRecordInfo<
      '/posts/manual-neovim-lazyvim',
      '/posts/manual-neovim-lazyvim',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-programming-fonts': RouteRecordInfo<
      '/posts/manual-programming-fonts',
      '/posts/manual-programming-fonts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-project-create': RouteRecordInfo<
      '/posts/manual-project-create',
      '/posts/manual-project-create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-ts-advanced-grammar': RouteRecordInfo<
      '/posts/manual-ts-advanced-grammar',
      '/posts/manual-ts-advanced-grammar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-vue-advanced-grammar': RouteRecordInfo<
      '/posts/manual-vue-advanced-grammar',
      '/posts/manual-vue-advanced-grammar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/manual-windows-setup': RouteRecordInfo<
      '/posts/manual-windows-setup',
      '/posts/manual-windows-setup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/misc-bun-vs-nodejs': RouteRecordInfo<
      '/posts/misc-bun-vs-nodejs',
      '/posts/misc-bun-vs-nodejs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/misc-first-time-trying-roller-coaster': RouteRecordInfo<
      '/posts/misc-first-time-trying-roller-coaster',
      '/posts/misc-first-time-trying-roller-coaster',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/misc-vite-and-unbundled': RouteRecordInfo<
      '/posts/misc-vite-and-unbundled',
      '/posts/misc-vite-and-unbundled',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project-engineering-categorize-your-dependencies': RouteRecordInfo<
      '/posts/project-engineering-categorize-your-dependencies',
      '/posts/project-engineering-categorize-your-dependencies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/project-engineering-manually-split-chunks': RouteRecordInfo<
      '/posts/project-engineering-manually-split-chunks',
      '/posts/project-engineering-manually-split-chunks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/test-recursive-mono-nbsp-rendering': RouteRecordInfo<
      '/posts/test-recursive-mono-nbsp-rendering',
      '/posts/test-recursive-mono-nbsp-rendering',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects': RouteRecordInfo<
      '/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/sponsors-list': RouteRecordInfo<
      '/sponsors-list',
      '/sponsors-list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use': RouteRecordInfo<
      '/use',
      '/use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
    }
    'pages/bookmarks.md': {
      routes:
        | '/bookmarks'
      views:
        | never
    }
    'pages/demos.md': {
      routes:
        | '/demos'
      views:
        | never
    }
    'pages/media.md': {
      routes:
        | '/media'
      views:
        | never
    }
    'pages/notes.md': {
      routes:
        | '/notes'
      views:
        | never
    }
    'pages/photos.md': {
      routes:
        | '/photos'
      views:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/code-style-encapsulation-and-modularity.md': {
      routes:
        | '/posts/code-style-encapsulation-and-modularity'
      views:
        | never
    }
    'pages/posts/code-style-symbol-name-pattern.md': {
      routes:
        | '/posts/code-style-symbol-name-pattern'
      views:
        | never
    }
    'pages/posts/manual-bash-script.md': {
      routes:
        | '/posts/manual-bash-script'
      views:
        | never
    }
    'pages/posts/manual-computer-network.md': {
      routes:
        | '/posts/manual-computer-network'
      views:
        | never
    }
    'pages/posts/manual-git.md': {
      routes:
        | '/posts/manual-git'
      views:
        | never
    }
    'pages/posts/manual-html-advanced-grammar.md': {
      routes:
        | '/posts/manual-html-advanced-grammar'
      views:
        | never
    }
    'pages/posts/manual-js-advanced-grammar.md': {
      routes:
        | '/posts/manual-js-advanced-grammar'
      views:
        | never
    }
    'pages/posts/manual-js-pm.md': {
      routes:
        | '/posts/manual-js-pm'
      views:
        | never
    }
    'pages/posts/manual-neovim-lazyvim.md': {
      routes:
        | '/posts/manual-neovim-lazyvim'
      views:
        | never
    }
    'pages/posts/manual-programming-fonts.md': {
      routes:
        | '/posts/manual-programming-fonts'
      views:
        | never
    }
    'pages/posts/manual-project-create.md': {
      routes:
        | '/posts/manual-project-create'
      views:
        | never
    }
    'pages/posts/manual-ts-advanced-grammar.md': {
      routes:
        | '/posts/manual-ts-advanced-grammar'
      views:
        | never
    }
    'pages/posts/manual-vue-advanced-grammar.md': {
      routes:
        | '/posts/manual-vue-advanced-grammar'
      views:
        | never
    }
    'pages/posts/manual-windows-setup.md': {
      routes:
        | '/posts/manual-windows-setup'
      views:
        | never
    }
    'pages/posts/misc-bun-vs-nodejs.md': {
      routes:
        | '/posts/misc-bun-vs-nodejs'
      views:
        | never
    }
    'pages/posts/misc-first-time-trying-roller-coaster.md': {
      routes:
        | '/posts/misc-first-time-trying-roller-coaster'
      views:
        | never
    }
    'pages/posts/misc-vite-and-unbundled.md': {
      routes:
        | '/posts/misc-vite-and-unbundled'
      views:
        | never
    }
    'pages/posts/project-engineering-categorize-your-dependencies.md': {
      routes:
        | '/posts/project-engineering-categorize-your-dependencies'
      views:
        | never
    }
    'pages/posts/project-engineering-manually-split-chunks.md': {
      routes:
        | '/posts/project-engineering-manually-split-chunks'
      views:
        | never
    }
    'pages/posts/test-recursive-mono-nbsp-rendering.md': {
      routes:
        | '/posts/test-recursive-mono-nbsp-rendering'
      views:
        | never
    }
    'pages/projects.md': {
      routes:
        | '/projects'
      views:
        | never
    }
    'pages/sponsors-list.md': {
      routes:
        | '/sponsors-list'
      views:
        | never
    }
    'pages/use.md': {
      routes:
        | '/use'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
