/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/encapsulation-and-modularity': RouteRecordInfo<'/posts/encapsulation-and-modularity', '/posts/encapsulation-and-modularity', Record<never, never>, Record<never, never>>,
    '/posts/first-time-trying-roller-coaster': RouteRecordInfo<'/posts/first-time-trying-roller-coaster', '/posts/first-time-trying-roller-coaster', Record<never, never>, Record<never, never>>,
    '/posts/git-manual': RouteRecordInfo<'/posts/git-manual', '/posts/git-manual', Record<never, never>, Record<never, never>>,
    '/posts/js-advanced-grammar-manual': RouteRecordInfo<'/posts/js-advanced-grammar-manual', '/posts/js-advanced-grammar-manual', Record<never, never>, Record<never, never>>,
    '/posts/project-create-manual': RouteRecordInfo<'/posts/project-create-manual', '/posts/project-create-manual', Record<never, never>, Record<never, never>>,
    '/posts/symbol-name-pattern-manual': RouteRecordInfo<'/posts/symbol-name-pattern-manual', '/posts/symbol-name-pattern-manual', Record<never, never>, Record<never, never>>,
    '/posts/windows-setup-manual': RouteRecordInfo<'/posts/windows-setup-manual', '/posts/windows-setup-manual', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes: '/'
      views: never
    }
    'pages/[...404].md': {
      routes: '/[...404]'
      views: never
    }
    'pages/bookmarks.md': {
      routes: '/bookmarks'
      views: never
    }
    'pages/demos.md': {
      routes: '/demos'
      views: never
    }
    'pages/media.md': {
      routes: '/media'
      views: never
    }
    'pages/notes.md': {
      routes: '/notes'
      views: never
    }
    'pages/photos.md': {
      routes: '/photos'
      views: never
    }
    'pages/posts/index.md': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/encapsulation-and-modularity.md': {
      routes: '/posts/encapsulation-and-modularity'
      views: never
    }
    'pages/posts/first-time-trying-roller-coaster.md': {
      routes: '/posts/first-time-trying-roller-coaster'
      views: never
    }
    'pages/posts/git-manual.md': {
      routes: '/posts/git-manual'
      views: never
    }
    'pages/posts/js-advanced-grammar-manual.md': {
      routes: '/posts/js-advanced-grammar-manual'
      views: never
    }
    'pages/posts/project-create-manual.md': {
      routes: '/posts/project-create-manual'
      views: never
    }
    'pages/posts/symbol-name-pattern-manual.md': {
      routes: '/posts/symbol-name-pattern-manual'
      views: never
    }
    'pages/posts/windows-setup-manual.md': {
      routes: '/posts/windows-setup-manual'
      views: never
    }
    'pages/projects.md': {
      routes: '/projects'
      views: never
    }
    'pages/sponsors-list.md': {
      routes: '/sponsors-list'
      views: never
    }
    'pages/use.md': {
      routes: '/use'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
